name: Main

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      - name: install mariadb lib
        run: sudo apt-get install -y libmariadb-dev
      - name: setup python
        uses: py-actions/py-dependency-install@v2
        with:
          path: "testing/requirements.txt"
      - name: Setup DB
        env:
            DATABASE_URL: mysql://user:password@127.0.0.1:${{ job.services.mariadb.ports[3306] }}/test
        run: python testing/x.py

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-build-${{ matrix.runtime }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Test
        env:
            DATABASE_URL: mysql://root:password@127.0.0.1:${{ job.services.mariadb.ports[3306] }}/test
            RUST_BACKTRACE: 1
        run: cargo test -- --nocapture

      - name: Build
        env:
            DATABASE_URL: mysql://user:password@127.0.0.1:${{ job.services.mariadb.ports[3306] }}/test
        run: cargo build
      
      - run: rustup component add clippy
      - name: clippy lints
        env:
            DATABASE_URL: mysql://user:password@127.0.0.1:${{ job.services.mariadb.ports[3306] }}/test
        run: cargo clippy
