name: Rust

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

    #  - name: Test
    #    env:
    #        DATABASE_URL: mysql://user:test@localhost:${{ job.services.mariadb.ports[3306] }}/test
    #    run: cargo test

      - name: Build
        env:
            DATABASE_URL: mysql://user:test@localhost:${{ job.services.mariadb.ports[3306] }}/test
        run: cargo build